# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51752934915446c936f45689e01237e5afbab16990c30a64e5f17fbdba321558087abd4531876610249822d8d73a4e724c674c02b27e78a2304320cccf08a760

test:
  secret_key_base: 2649275778661f2718d01bcf232d40b0a8fdbcf1b794f285cd14cc40acdf07174cfe3b200c61eed11395486d5e74f63cd61278b9e9f21c93c5ec4fc0f2abd0ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
